question_data = [
    {"question": "The human brain is the largest organ in the human body.", "answer": 'False'},
    {"question": "Mount Everest is the tallest mountain in the world.", "answer": 'True'},
    {"question": "The Pacific Ocean is the largest ocean on Earth.", "answer": 'True'},
    {"question": "Goldfish have a three-second memory span.", "answer": 'False'},
    {"question": "The Mona Lisa was painted by Vincent van Gogh.", "answer": 'False'},
    {"question": "Humans and dinosaurs coexisted.", "answer": 'False'},
    {"question": "The speed of light is approximately 299,792 kilometers per second.", "answer": 'True'},
    {"question": "The Great Wall of China is longer than the distance between the Earth and the Moon.", "answer": False},
    {"question": "The largest desert in the world is the Sahara Desert.", "answer": False},
    {"question": "The chemical symbol for gold is Au.", "answer": True},
    {"question": "A group of lions is called a pride.", "answer": True},
    {"question": "Shakespeare was born in the 18th century.", "answer": False},
    {"question": "The Great Barrier Reef is located in the Atlantic Ocean.", "answer": False},
    {"question": "Human blood is blue inside the body before it is exposed to oxygen.", "answer": False},
    {"question": "Venus is the only planet in our solar system that rotates clockwise.", "answer": True},
    {"question": "Albert Einstein won the Nobel Prize in Literature.", "answer": False},
    {"question": "The Amazon Rainforest is often referred to as the 'lungs of the Earth' "
                 "due to its role in producing oxygen.", "answer": True},
    {"question": "The Eiffel Tower was originally intended to be a temporary exhibit.", "answer": True},
    {"question": "Cows have four stomachs.", "answer": True},
    {"question": "Lightning never strikes the same place twice.", "answer": False},
    {"question": "The chemical formula for water is H2O.", "answer": True},
    {"question": "The Earth is closer to the Sun than Venus.", "answer": False},
    {"question": "The Nobel Prize is awarded annually for achievements in six categories: Peace, Literature, Medicine, Physics, Chemistry, and Economic Sciences.", "answer": True},
    {"question": "An octopus has three hearts.", "answer": True},
    {"question": "There are 206 bones in the adult human body.", "answer": True},
    {"question": "The Atlantic Ocean is the smallest ocean in the world.", "answer": False},
    {"question": "Jupiter is the largest planet in our solar system.", "answer": True},
    {"question": "Hummingbirds are the only birds that can fly backward.", "answer": True},
    {"question": "The Pyramids of Giza are located in Mexico.", "answer": False},
    {"question": "The currency of Japan is the yen.", "answer": True},
    {"question": "Venus is named after the Roman goddess of love and beauty.", "answer": True},
    {"question": "Einstein’s theory of relativity was published in 1905.", "answer": True},
    {"question": "The fastest land animal is the cheetah.", "answer": True},
    {"question": "The Dead Sea is a sea located in the Mediterranean region.", "answer": False},
    {"question": "Sharks are older than trees.", "answer": True},
    {"question": "There are seven continents on Earth.", "answer": True},
    {"question": "The currency of Brazil is the peso.", "answer": False},
    {"question": "The first human to journey into outer space was Yuri Gagarin.", "answer": True},
    {"question": "The longest river in the world is the Nile River.", "answer": True},
    {"question": "Humans share 50% of their DNA with bananas.", "answer": True},
    {"question": "Giraffes have the same number of neck vertebrae as humans.", "answer": False}
]